#!/usr/bin/env python3
"""
Generate the seed CSVs for the Une Faible Impression production tracker.

Source: Zoom meeting notes 2026-08-30 (Scenes 1-4, budget, crew) and
2026-09-02 (Scenes 3-8, equipment, costume).

These CSVs are only the INITIAL import. Once the data is in Google Sheets,
the Sheet is the master and this script is just a record of how it started.
Re-run:  python3 generate_seed_csvs.py
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))

SCENE_HEADER = [
    "Scene", "Shot", "Item / Decision", "Category", "Status", "Priority",
    "Owner", "Needs input from", "Deadline", "Options / Notes", "Source",
]

# Status vocabulary: Blocked | Open | Leaning | Decided | Deferred
# Priority vocabulary: P1 (before shoot) | P2 (before scout) | P3 (nice-to-have)

SCENE_ROWS = [
    # ---------------- SCENE 1 ----------------
    ["1", "Shot 1", "Dolly surface for the opening push: run on concrete as-is vs. lay dance floors vs. lay tracks + remove in VFX",
     "Equipment", "Blocked", "P1", "Shafi", "Sam, Alex", "Mon location scout",
     "Path to the bench is concrete with a possible slight slope. (a) roll on concrete = shake risk; (b) dance floors; (c) tracks removed in VFX. Sam: scout whether the concrete is smooth enough to roll without tracks before committing to VFX removal. Decide on-site.",
     "8/30"],
    ["1", "Shot 1", "Writing legibility over-the-shoulder is not a priority",
     "Camera/Move", "Decided", "P3", "", "", "",
     "On a ~30mm wide/medium lens legibility is limited; team agreed seeing that he is writing is enough - the voiceover carries the content.",
     "8/30"],
    ["1", "Shot 2", "Pedestal vs. tilt-down to the notebook before the pan-right to the woman",
     "Camera/Move", "Leaning", "P2", "", "", "Mon location scout",
     "Camera drops to the notebook, pans right across the ground (leaves / wind), reveals the woman's legs, then tilts up to finish on her sitting on a bollard. Pedestal-or-tilt not locked.",
     "8/30"],
    ["1", "Shot 2", "Woman sits on a bollard, not a parallel bench",
     "Blocking", "Decided", "P3", "", "", "",
     "Script originally placed her on a parallel bench; changed to a bollard to avoid a cheesy symmetry.",
     "8/30"],
    ["1", "Shots 3 & 4", "Deliberate 180-degree-rule break for the conversation coverage - test before committing",
     "Blocking", "Open", "P1", "Shafi, Ishmam", "Sam", "Mon scout / actor rehearsal",
     "Man's angle: on-axis side profile. Woman's angle: from behind and slightly to the side, only half her face. Goal: the audience never has spatial certainty about where she is relative to him (real / imagined / ghostly). The unconventional cutting may feel jarring - plan to test it in practice first.",
     "8/30"],
    ["1", "Shot 5", "Sparing full-spatial establishing shot",
     "Camera/Move", "Leaning", "P2", "", "", "",
     "One shot that reveals both characters in frame to establish their relative positions; used sparingly so the spatial ambiguity is not fully resolved. Placement within the scene still TBD.",
     "8/30"],
    ["1", "Shot 8", "Woman's exit and re-entry direction",
     "Blocking", "Leaning", "P2", "Shafi, Ishmam", "", "Mon location scout",
     "She walks off (likely camera right); camera pans right across nature without her; she reappears from the same or the opposite side. Intent: naturalistic, not ghostly, but the audience briefly loses track of her. Leaning naturalistic; not finalized.",
     "8/30"],
    ["1", "Closing", "Wind / fan rig for the paper fly-away",
     "VFX/Equipment", "Open", "P1", "Shafi", "Wind-rig team", "Build + Mon scout",
     "Friends recruited to engineer a wind/fan rig so the paper looks genuinely caught in the wind, not just dropped. May also grab a shot of the paper in the air for editorial flexibility. Possible cut to the woman: 'It has a rebellious turn of mind,' + footsteps chasing the paper. See reference-docs/ufi-wind-rig-responsibility-matrix.",
     "8/30"],
    ["1", "All", "Scene 1 is the most technically complex / shot-dense sequence (~8-9 shots, ~3.5 script pages)",
     "Schedule", "Open", "P2", "", "Sam", "",
     "Flagged as the shot-count and time risk for the schedule. Track against the 10-12 shots/day guidance.",
     "8/30"],

    # ---------------- SCENE 2 ----------------
    ["2", "Shot 1 (walk)", "Shoulder rig vs. static-with-slight-reframe to follow the boy walking",
     "Camera/Move", "Open", "P2", "Shafi, Ishmam", "Sam", "Mon location scout",
     "After the boy hears his name and stands, the camera pedestals up with him then follows. Shoulder rig is preferred for the naturalistic feel and time efficiency, but conflicts with the film's settled aesthetic. Not chosen.",
     "8/30"],
    ["2", "All", "Memory-scene look: higher frame rate + a slight colour-grade shift",
     "VFX/Color", "Open", "P2", "Shafi", "Alex (colourist)", "Mon location scout",
     "Memory scenes (2 & 4) should read slightly different from the main timeline - shoot at a higher fps and slow ~0.9x in post, plus a subtle grade variation (not black-and-white). Confirm the approach with Alex on the Monday scout.",
     "8/30"],
    ["2", "Shot 1", "Tree deliberately framed on the right for a later match cut",
     "Camera/Move", "Decided", "P3", "", "", "",
     "Boy digs in the dirt near a large tree positioned frame-right; it rhymes with the woman's background position in Scene 3's opening.",
     "8/30"],

    # ---------------- SCENE 3 ----------------
    ["3", "Shots 1-2", "Split the following shot into two (before / after the cut to the boy) with a closer reframe on the return",
     "Camera/Move", "Leaning", "P2", "", "", "",
     "Dolly follows the man & woman from behind on tracks (the road surface allows it). They pause, look up; the camera tilts up but cuts before revealing what they see.",
     "8/30, 9/2"],
    ["3", "Tilt", "Where to cut the upward tilt",
     "VFX/Edit", "Leaning", "P2", "", "", "Edit",
     "Plan is to tilt all the way up and decide the exact cut point in editing.",
     "9/2"],
    ["3", "Opening", "Man-picks-up-paper: the woman's background position echoes the memory-shot tree",
     "Camera/Move", "Decided", "P3", "", "", "",
     "Static shot; paper lands on the road, the man enters and leans to pick it up, the woman enters and walks to a background position that visually rhymes with the tree. The paper prop must match Scene 1's fly-away exactly (same fold / crumple).",
     "8/30"],

    # ---------------- SCENE 4 ----------------
    ["4", "All", "Tilt-angle continuity between Scene 3's up-look and Scene 4's opening",
     "Camera/Move", "Open", "P1", "Shafi, Ishmam", "", "Mon scout / edit",
     "The cut must pick up at roughly the same tilt angle or the transition jumps. May be partially fixable in editing. Leading approach: Scene 4 starts high on the trees and tilts DOWN to reveal the boy (Option A), rather than continuing the upward tilt (Option B, which risks a compositional mismatch since the camera would be above the boy).",
     "9/2"],
    ["4", "All", "Higher frame rate (shoot 30fps, deliver 24fps) for a subtle slow-motion",
     "Camera/Move", "Open", "P1", "Shafi", "Sam, Alex", "Sam / Alex meeting",
     "Not full slow-motion (60fps would be too extreme). To be confirmed with Sam and Alex.",
     "9/2"],
    ["4", "All", "High-angle-looking-down composition, largely static",
     "Camera/Move", "Leaning", "P2", "", "", "Mon location scout",
     "Preferred: a high angle down on the boy walking through the forest, on uneven downhill terrain. Static, given the difficulty of moving equipment at height. Boy hears his name, looks around briefly, walks off screen.",
     "9/2"],
    ["4", "All", "Shafi to draw a revised frame showing the trees-first / tilt-down composition",
     "Camera/Move", "Open", "P2", "Shafi", "", "Before storyboard printing",
     "Action item from 9/2 - needed for the storyboard set.",
     "9/2"],

    # ---------------- SCENE 5 ----------------
    ["5", "Shot 2", "Add a slight dolly move to the 'painting shot'",
     "Camera/Move", "Open", "P2", "Shafi", "", "Shot-list update",
     "Shot 2: the woman looks up (not at the man - as if something made her stop), the man enters screen-right and freezes; held mostly static. Action item: annotate the slight dolly on the shot list. The static frame constrains composition flexibility.",
     "9/2"],
    ["5", "Shot 6", "Getting a dolly up the staircase",
     "Equipment", "Blocked", "P1", "Shafi, Ishmam", "Sam, Alex, Bad Dog", "Bad Dog visit (Sat)",
     "The Fisher dolly up a staircase may be impossible. Alternatives: a smaller rental dolly from Bad Dog, or a shoulder rig for that shot only. The shoulder rig gives an unsettled, hovering look inconsistent with the Tarkovsky-influenced aesthetic.",
     "9/2"],
    ["5", "Shots 4-7", "Ishmam to hand-draw rough compositions for shots 4, 5, 6, 7",
     "Blocking", "Open", "P1", "Ishmam", "", "Thursday night",
     "So Shafi can generate AI reference images. Shot 6 = walking down stairs. Shot 7 = wide shot, characters walking left-to-right in a park-like setting, functions as an insert over continuing dialogue.",
     "9/2"],
    ["5", "Shot 7", "Location for the insert wide - park-ish but not overtly, and must match the previous location",
     "Location", "Open", "P2", "Shafi, Ishmam", "", "Mon location scout",
     "Wide shot of the characters walking left-to-right; needs to read as park-like without being obviously a park, and must visually match the preceding location.",
     "9/2"],
    ["5", "Shot 8", "Seating location + elevation for the woman/man depth composition",
     "Location", "Leaning", "P1", "Shafi, Ishmam", "", "Before Monday scout",
     "Woman sits low (log / stump height, not bollard height, which puts her near standing height); the man is positioned lower on a slope so their faces sit at a similar elevation for the pan. Favoured: the area where Ishmam & Ishiko were at different elevations. Rejected: the cut-off stump near the first park bench (feels like returning to an earlier location).",
     "9/2"],
    ["5", "Shot 8", "Source or bring a wooden stump as a production-design element",
     "Costume/PD", "Open", "P2", "Shafi, Ishmam", "", "Before shoot",
     "May need to bring a wooden stump to location for the woman's seat.",
     "9/2"],
    ["5", "Shot 9", "Lens choice for the dolly-in -> tilt-down -> pan-to-man",
     "Camera/Move", "Open", "P1", "Shafi", "Sam", "Sam / Alex meeting",
     "The dolly pushes in on the woman, tilts down to the book / hands, then pans left to the man's face at roughly the same elevation. Must keep the man's face in frame through the pan - a longer lens risks clipping it. Dolly tracks needed on grass.",
     "9/2"],
    ["5", "All", "Whether to simplify Scene 5 if the schedule tightens",
     "Schedule", "Deferred", "P2", "", "Sam", "",
     "Scene 5 is the longest / most complex scene and the identified candidate for cuts under schedule pressure.",
     "8/30, 9/2"],
    ["5", "All", "Scene 5 is the longest scene (multi-location, most dialogue) - roughly 9 shots / 200 words",
     "Schedule", "Open", "P2", "", "", "",
     "The other long / complex scene alongside Scene 1. Watch shot count and the time cost of long takes.",
     "9/2"],

    # ---------------- SCENE 6 ----------------
    ["6", "Opening", "Pedestal vs. tilt-up from the forest floor to reveal the bed",
     "Camera/Move", "Leaning", "P2", "", "", "Mon location scout",
     "A low-to-high move revealing the bed; the boy stops at the edge. Pedestal-or-tilt not locked.",
     "9/2"],
    ["6", "All", "Can the location be shot on a tripod without a dolly?",
     "Equipment", "Open", "P2", "Shafi, Ishmam", "Sam", "Mon location scout",
     "The location is the far end of the interview woods area; it may be tripod-able. Needs scout confirmation - ties into the dolly-transport problem.",
     "9/2"],
    ["6", "Jump sequence", "One continuous shot vs. cutting to the fabric-grip insert",
     "VFX/Edit", "Open", "P1", "Shafi, Ishmam", "Sam", "Mon location scout",
     "Preferred: shoot the whole jumping sequence in one shot (camera tilts up over the first 1-2 jumps, holds at sky level, boy jumps in and out of frame, spins mid-air, camera tilts back down). If the dolly can't reach the location or it is too technically difficult, cut to a close-up insert of the boy gripping the bed fabric as a natural break.",
     "9/2"],
    ["6", "Jump sequence", "Camera parallel to the bed vs. bed angled with the boy parallel to camera",
     "Camera/Move", "Open", "P2", "", "", "Test on scout",
     "To be tested on location.",
     "9/2"],
    ["6", "Jump sequence", "Add the 'boy gripping bed fabric' insert to the shot list",
     "VFX/Edit", "Open", "P2", "Shafi", "", "Shot-list update",
     "Contingency insert if the one-shot can't be executed. Action item from 9/2.",
     "9/2"],
    ["6", "Final shot", "Ruckenfigur -> slow pan to the woman near the tree line",
     "Camera/Move", "Decided", "P3", "", "", "",
     "Boy seen from behind looks back, camera holds, then pans slowly to the woman standing almost against the trees in the distance.",
     "9/2"],

    # ---------------- SCENE 7 ----------------
    ["7", "Pre-pan", "What to cut to between the argument climax and the Tarkovsky pan",
     "VFX/Edit", "Open", "P1", "Shafi, Ishmam", "Sam", "Before shoot",
     "A cut is needed between the argument and the pan. Cutting to the boy risks giving him a premature conclusion. Leading candidate: cut to the soil / earth from the earlier forest scene (no boy, just the ground he was digging).",
     "9/2"],
    ["7", "Tarkovsky pan", "Bollard placement for the pan's first stop - road & houses visible in the background",
     "Location", "Open", "P1", "Shafi, Ishmam", "Sam", "Mon location scout",
     "The pan opens near where the couple sits and moves across the field; the first stop is the now-empty bollards. Shooting back toward the real bollards shows the road and houses. Options: (a) move the bollards to a different position in the field (symbolic / supernatural placement) or (b) include the bollards only briefly before panning to the couple.",
     "9/2"],
    ["7", "Tarkovsky pan", "Zoom lens for the pan (zoomed in at the start, zooms out for depth)",
     "Equipment", "Open", "P2", "Shafi", "Sam", "Bad Dog visit",
     "The Tarkovsky reference uses a zoom lens and layered composition (grass / dirt / trees / secondary trees / sun). Need to confirm a zoom lens is available; this conflicts with the same-lens-per-sequence rule and needs thought.",
     "9/2"],
    ["7", "Tarkovsky pan", "End the pan on a tilt-down (the reference likely uses a crane)",
     "Camera/Move", "Decided", "P3", "", "", "",
     "Their version will use a tilt rather than a crane move.",
     "9/2"],
    ["7", "All", "Actors must fully memorise lines for this scene (single static shot, dialogue-heavy)",
     "Blocking", "Open", "P2", "Shafi", "Tyler, Holly", "Actor rehearsals",
     "Most of the scene is one static shot with heavy dialogue; ADR covers the rest of the film but this scene needs the performance on the day.",
     "9/2"],
    ["7", "All", "Blocking: the man turns sideways (screen right) at the argument climax, not fully back-to-camera",
     "Blocking", "Decided", "P3", "", "", "",
     "Characters sit apart and converse; the woman stands and turns away; the man crosses the implied barrier first, the woman follows.",
     "9/2"],

    # ---------------- SCENE 8 ----------------
    ["8", "All", "Jacket continuity: does the old woman wear the younger woman's jacket?",
     "Costume/PD", "Leaning", "P2", "Shafi", "Ishika", "Before shoot",
     "The same jacket could imply a generational link (mother's jacket handed down) but risks being too on-the-nose. Leaning toward redressing the old woman entirely.",
     "9/2"],
    ["8", "All", "Old-woman costume: a granny-style sundress that hangs full-length with a small layer over it",
     "Costume/PD", "Leaning", "P2", "Shafi", "Ishika, Holly", "Before shoot",
     "Separate from the younger woman's clothes. Need Holly's sizing for a fitting reference. Action item: Shafi to brief Ishika.",
     "9/2"],
    ["8", "All", "Shoot the old-woman shots last of the day",
     "Schedule", "Decided", "P2", "", "Holly", "Shoot day",
     "Holly's old-age makeup process is irreversible for that session.",
     "9/2"],
    ["8", "All", "Shoot both the side-of-street and the interview locations",
     "Location", "Decided", "P3", "", "", "",
     "Side-of-street (shot from the far side) confirmed by a Fujifilm photo reference. Shoot both to have options in the edit. The woman is distant enough that makeup detail matters less than the clothing silhouette.",
     "9/2"],

    # ---------------- CROSS-SCENE / SHOT DESIGN ----------------
    ["All", "Inserts", "Build a dedicated insert list for every scene",
     "VFX/Edit", "Open", "P2", "Shafi, Ishmam", "Sam, Alex", "Mon location scout",
     "Sam regretted not doing this on his own shoot. Nature (light through leaves, wind in grass, leaves on the ground), prop close-ups (notebook, pen, paper, a corner of the dress), walking cutaways, symbolically significant objects as bookends. Lock the specifics on the Monday scout with Alex.",
     "8/30"],
    ["All", "Inserts", "Keep the total shot count deliberate - currently 29, inserts could push it toward ~40",
     "Schedule", "Open", "P2", "", "Sam", "",
     "Sam: 36 is 'completely fine'; also identify 5-10 nice-to-have bonus shots to attempt only if time permits, without compromising the core story.",
     "8/30, 9/2"],
    ["2-4", "Coverage", "Add closer shots (mediums / close-ups) - scenes 2-4 currently skew wide",
     "Camera/Move", "Open", "P2", "Shafi, Ishmam", "Sam", "Storyboards",
     "Sam emphasised shot variation for emotional connection, especially in scenes 2-4.",
     "8/30"],
    ["All", "Lens", "Same lens for every shot within a sequence",
     "Camera/Move", "Decided", "P2", "", "", "",
     "Consistency rule for pans and tilts. Note the tension with the Scene 7 zoom-lens idea.",
     "9/2"],
    ["All", "Camera", "Frame rate: 24fps standard; 30fps for the forest / boy scenes; 60fps rejected",
     "Camera/Move", "Leaning", "P2", "", "Sam, Alex", "Sam / Alex meeting",
     "Allows a subtle slow-down in post for the memory scenes. Confirm with Sam and Alex.",
     "9/2"],
    ["All", "Camera", "Dolly tracks required on grass for the outdoor scenes",
     "Equipment", "Decided", "P2", "", "", "",
     "Plan the rental and transport accordingly.",
     "9/2"],
]

OVERALL_HEADER = [
    "Area", "Item / Concern", "Category", "Status", "Priority",
    "Owner", "Needs input from", "Deadline", "Notes", "Source",
]

OVERALL_ROWS = [
    ["Crew", "Gaffer still unconfirmed", "Crew", "Blocked", "P1", "Sam", "", "ASAP",
     "Sam to follow up.", "8/30"],
    ["Crew", "1st AC not yet confirmed", "Crew", "Open", "P1", "Sam", "", "ASAP",
     "Sam's 1st AC is currently on 'The Streak' (a basketball comedy shooting at SLU); expected to confirm availability soon.", "8/30"],
    ["Crew", "Dolly grip - Adrian unresponsive", "Crew", "Blocked", "P1", "Sam", "Bad Dog", "ASAP",
     "Sam to chase Adrian and also contact Bad Dog directly to source a dolly grip.", "8/30"],
    ["Crew", "Editor not locked", "Crew", "Open", "P2", "Sam", "", "Post-shoot OK",
     "Sam's editor contact is interested; Sam to send project info and gauge interest.", "8/30"],
    ["Crew", "Confirm Sam's own schedule for the shoot weekend + Monday", "Crew", "Open", "P2", "Sam", "", "",
     "Action item from 8/30.", "8/30"],
    ["Equipment", "Fisher dolly transport - stairs & deep forest", "Equipment", "Blocked", "P1",
     "Shafi, Ishmam", "Sam, Alex, Bad Dog", "Bad Dog visit (Sat) + Mon scout",
     "The Fisher may not be portable enough for the Scene 5 staircase or the Scene 6 forest location. Fallbacks: a smaller Bad Dog rental dolly for those shots, or a shoulder rig (aesthetic conflict). No confirmed solution.",
     "8/30, 9/2"],
    ["Equipment", "Shoulder rig vs. the film's settled aesthetic", "Equipment", "Open", "P2",
     "Shafi, Ishmam", "Sam", "",
     "The shoulder rig is the fallback for stairs / forest / slow-mo but both directors feel it produces an unsettled, hovering look at odds with the Tarkovsky-influenced language. It may suit the slow-mo forest shots if smooth enough.",
     "9/2"],
    ["Equipment", "Confirm the Bad Dog dolly return window + rental terms", "Equipment", "Open", "P2",
     "Shafi", "Sam, Andy (Bad Dog)", "Before pickup (the 23rd)",
     "Pickup 3-5 PM on the 23rd, return before 10 AM on the 26th. Sam thinks Bad Dog won't penalise a few hours' overage but says to confirm directly. Also decide daily vs. weekly rental terms.",
     "8/30"],
    ["Budget", "Kickstarter outcome vs. the budget gap", "Budget", "Open", "P1",
     "Shafi, Ishmam", "", "Campaign closes ~3 weeks after 8/30",
     "Revised budget ~$16,000 (up from ~$12,500). Sam projects ~$10k gross / ~$8k net. Shafi and Ishmam are each willing to contribute ~$5k to cover the gap. Funds don't land until 2 weeks after the campaign closes; vendors are net-30 so timing should be OK. Keep pushing the campaign.",
     "8/30"],
    ["Budget", "Chase in-kind support from local production companies", "Budget", "Open", "P3",
     "Shafi", "", "",
     "Sam's suggestion - location access, craft services, etc. rather than cash, per his St. Louis experience.",
     "8/30"],
    ["Budget", "Third shoot day adds ~20% to the budget", "Budget", "Decided", "P2", "", "", "",
     "Mostly extra dolly rental, craft services, insurance. Accepted. If the shot count stays ~30, day 3 can be Tyler-only + nature inserts to keep crew / insurance low.",
     "8/30"],
    ["Cast", "Asking Tyler & Holly for two full location days is a big ask", "Cast", "Open", "P2",
     "Shafi", "Tyler, Holly", "",
     "They're volunteering. The second scout / test shoot is the Sept 25 weekend; a second full test day with actors is possible in early October.",
     "9/2"],
    ["Cast", "Confirm Tyler for the Monday half-day shoot", "Cast", "Open", "P2", "Shafi", "Tyler", "Before shoot",
     "Day 3 is a half-day likely featuring only Tyler (possibly Basil).", "8/30"],
    ["Cast", "Reach out to Basil about Monday availability", "Cast", "Open", "P3", "Shafi", "Basil", "Before Monday",
     "If Basil is free, 1-2 of his shots (needing Holly or a stand-in) could be captured on the half-day.", "8/30"],
    ["Production Design", "Log availability for the bed frame may drop as summer ends", "Production Design", "Open", "P2",
     "Shafi, Ishmam", "", "Log marketplace visit (Sat)",
     "Visit the log marketplace Saturday. Unclear whether logs are more available in summer - check the logging season.",
     "9/2"],
    ["Production Design", "Source or bring a wooden stump for the Scene 5 seating", "Production Design", "Open", "P2",
     "Shafi, Ishmam", "", "Before shoot",
     "Cross-ref Scene 5 Shot 8. May need to bring a stump to location.", "9/2"],
    ["Costume", "Brief Ishika on the old-woman costume direction", "Costume/PD", "Open", "P2", "Shafi", "Ishika", "",
     "Granny dress / full-length sundress with a small layer. Ties to the Scene 8 jacket-continuity question. Need Holly's sizing.",
     "9/2"],
    ["Costume", "Test Tyler's thrifted costume", "Costume/PD", "Open", "P3", "Shafi", "Tyler", "Monday fitting",
     "Thrifted clothes bought for ~$20-30; bring them this weekend for a Monday fitting on Tyler.", "9/2"],
    ["Schedule", "Three-day shoot confirmed (Sat / Sun / Mon half-day)", "Schedule", "Decided", "P2", "", "", "",
     "Sat & Sun with Holly and Tyler; Monday a lighter half-day (Tyler, possibly Basil). Dolly pickup the 23rd, return by 10 AM the 26th, so principal photography is the weekend of the 24th-26th.",
     "8/30"],
    ["Schedule", "Monday (Labor Day) location scout + test shoot", "Schedule", "Decided", "P1",
     "Shafi, Ishmam", "Sam, Alex", "Monday",
     "Sam and Alex confirmed. Goal: assess dolly surfaces, check sightlines, capture test footage - not make new creative decisions on-site. Bring the open-questions list.",
     "8/30"],
    ["Schedule", "Dolly day starts at sunrise", "Schedule", "Leaning", "P2", "", "Full crew", "Dolly day",
     "Scene 1's opening dolly shots are sunrise-dependent: a 6-7 AM call, aiming to wrap dolly work by 8:30-9 AM to return gear by 10 AM.",
     "8/30"],
    ["Schedule", "Hit 60-75% of blocking finalised before the September actor visit", "Schedule", "Open", "P1",
     "Shafi, Ishmam", "", "September actor visit",
     "At minimum lock the more technically difficult blocking.", "9/2"],
    ["Prep", "Print all storyboard materials before Friday", "Prep", "Open", "P2", "Shafi",
     "Ishmam (drawings by Thu night)", "Friday morning",
     "Shafi prints in Chicago (free printing access). Depends on Ishmam delivering the four hand-drawn Scene 5 shots by Thursday night.",
     "9/2"],
    ["Prep", "Email Andy at Bad Dog to arrange the Saturday visit", "Prep", "Open", "P2", "Shafi", "Andy (Bad Dog)", "Before Saturday",
     "Inspect the Fisher dolly, discuss rental terms (daily vs. weekly), the Fisher return window. Possibly also visit Horizon with Sam on Saturday.",
     "9/2"],
    ["Prep", "Share reference films & clipped shots with Sam", "Prep", "Open", "P3", "Shafi", "Sam", "Before the Sam meeting",
     "ShotDeck stills already pulled. References: Forrest Gump (tone / composition), Hamnet, Train to Dreams (Netflix), plus the specific Tarkovsky pan (~1'36, single take).",
     "8/30, 9/2"],
    ["Prep", "Both directors re-watch the Tarkovsky reference before the Sam meeting", "Prep", "Open", "P2",
     "Shafi, Ishmam", "", "Before the Sam meeting",
     "Be ready to show Sam the exact shot and articulate what to replicate. Acknowledged they lack Tarkovsky's resources (Soviet budget, a planted poppy field).",
     "9/2"],
    ["Process", "Documentation standard: thorough enough to shoot without Shafi & Ishmam present", "Process", "Open", "P2",
     "Shafi, Ishmam", "", "Ongoing",
     "Every shot clearly described and visualised. The guiding goal for the storyboard / shot-deck package.",
     "9/2"],
    ["Process", "Daily 5-minute standups + Jira-style task tracking from Tuesday", "Process", "Open", "P2",
     "Shafi, Ishmam", "Sam", "Tuesday",
     "Also build out the risk log with on-day contingencies.", "9/2"],
    ["Location", "October weather & leaf coverage", "Location", "Open", "P3", "", "", "",
     "The forecast looks warm (~70F), which helps outdoor shooting. Leaf coverage on the trees may affect depth in key shots.",
     "9/2"],
    ["Camera", "Lighting is primarily natural", "Camera", "Decided", "P3", "", "", "",
     "Outdoor setting; camera movement and production design are the primary tools for visual impact. An overhead-diffusion / negative-fill kit is still needed to control dappled canopy light (see the Scene 3 shoot-day notes).",
     "8/30"],
    ["Sound", "Full ADR planned", "Sound", "Decided", "P2", "", "", "",
     "Actors won't be cut for dialogue errors; cuts are driven by camera / composition only. This reduces pressure and allows more takes focused on movement and blocking.",
     "8/30"],
    ["Runtime", "Runtime estimate ~16 minutes, target under 20", "Schedule", "Decided", "P3", "", "", "",
     "Estimated with Claude from all available data using a 1-minute-minimum-per-scene constraint. A 15-minute cut is also achievable if needed.",
     "9/2"],
]


def write_csv(path, header, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
    print(f"wrote {path}  ({len(rows)} rows)")


if __name__ == "__main__":
    write_csv(os.path.join(HERE, "scene-shot-items.csv"), SCENE_HEADER, SCENE_ROWS)
    write_csv(os.path.join(HERE, "production-wide-concerns.csv"), OVERALL_HEADER, OVERALL_ROWS)
